### ISSUE TITLE
[QST] How does one run the `40_cutlass_py` example?

### ISSUE THREAD

**Issue by gmarkall** [NVIDIA/cutlass#529]
I'm attempting to run the CUTLASS Python example. So far I've added the folder `tools/library/scripts` to py `PYTHONPATH` and then attempted to run the example, but I get an NVRTC error:

```
$ python test-cutlass-py.py 
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/cutlass/examples/40_cutlass_py/test-cutlass-py.py", line 68, in <module>
    module = rt.Module('module.cu', [gemm], compilation_options)
  File "/home/gmarkall/numbadev/cutlass/tools/library/scripts/rt.py", line 669, in __init__
    self.compile_(compilation_options)
  File "/home/gmarkall/numbadev/cutlass/tools/library/scripts/rt.py", line 733, in compile_
    raise RuntimeError(error_string + self.log.decode() + self.source_buffer)
RuntimeError: NVRTC Error: 6
../../include/cutlass/integer_subbyte.h(39): catastrophic error: cannot open source file "cuda/std/cstdint"

1 catastrophic error detected in the compilation of "module.cu".
Compilation terminated.
#include "cutlass/cutlass.h"
#include "cutlass/numeric_types.h"
#include "cutlass/arch/arch.h"
#include "cutlass/arch/mma.h"
#include "cutlass/layout/matrix.h"
#include "cutlass/gemm/device/gemm.h"
#include "cutlass/gemm/device/gemm_universal_adapter.h"
#include "cutlass/gemm/kernel/default_gemm_universal.h"

// Gemm operator cutlass_simt_sgemm_128x128_8x2_nt_align1
using cutlass_simt_sgemm_128x128_8x2_nt_align1_base = 
  typename cutlass::gemm::kernel::DefaultGemmUniversal<
    float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 1,    // transposed B operand
    float, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 1,    // transposed A operand
    float, cutlass::layout::RowMajor,
    float,
    cutlass::arch::OpClassSimt,
    cutlass::arch::Sm50,
    cutlass::gemm::GemmShape<128, 128, 8>,
    cutlass::gemm::GemmShape<32, 64, 8>,
    cutlass::gemm::GemmShape<1, 1, 1>,
    
    cutlass::epilogue::thread::LinearCombination<
      float,
      1,
      float,
      float
    >
,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
    2,
    cutlass::arch::OpMultiplyAdd
>::GemmKernel;

// Define named type
struct cutlass_simt_sgemm_128x128_8x2_nt_align1_type : 
  public cutlass_simt_sgemm_128x128_8x2_nt_align1_base { };

extern "C"
__global__ void
cutlass_simt_sgemm_128x128_8x2_nt_align1(cutlass_simt_sgemm_128x128_8x2_nt_align1_type::Params params) {

  // Dynamic shared memory base pointer
  extern __shared__ int SharedStorageBase[];

  // Declare pointer to dynamic shared memory.
  cutlass_simt_sgemm_128x128_8x2_nt_align1_type::SharedStorage *shared_storage =
      reinterpret_cast<cutlass_simt_sgemm_128x128_8x2_nt_align1_type::SharedStorage *>(SharedStorageBase);

  cutlass_simt_sgemm_128x128_8x2_nt_align1_type op;

  op(params, *shared_storage);
}
```

I suspect I'm probably just doing something wrong, but I'm not quite sure what the right steps are - could you point me in the right direction please?

**Comment by gmarkall** [comment]
This was resolved by adding `/usr/local/cuda/include` to the `include_paths` list, which is at:

https://github.com/NVIDIA/cutlass/blob/f248e9bdb4a6e59bd665241f11cc76754b3c9429/examples/40_cutlass_py/test-cutlass-py.py#L61-L64
